export interface LanguageConfig {
  readonly name: string;
  readonly lang: string;
}

export const Languages: LanguageConfig[] = [
  { name: 'Plain Text', lang: 'plaintext' },
  { name: 'ABNF', lang: 'abnf' },
  { name: 'Access logs', lang: 'accesslog' },
  { name: 'Ada', lang: 'ada' },
  { name: 'Arduino (C++ w/Arduino libs)', lang: 'arduino' },
  { name: 'ARM assembler', lang: 'armasm' },
  { name: 'AVR assembler', lang: 'avrasm' },
  { name: 'ActionScript', lang: 'actionscript' },
  { name: 'AngelScript', lang: 'angelscript' },
  { name: 'Apache', lang: 'apache' },
  { name: 'AppleScript', lang: 'applescript' },
  { name: 'Arcade', lang: 'arcade' },
  { name: 'AsciiDoc', lang: 'asciidoc' },
  { name: 'AspectJ', lang: 'aspectj' },
  { name: 'AutoHotkey', lang: 'autohotkey' },
  { name: 'AutoIt', lang: 'autoit' },
  { name: 'Awk', lang: 'awk' },
  { name: 'Bash', lang: 'bash' },
  { name: 'Basic', lang: 'basic' },
  { name: 'BNF', lang: 'bnf' },
  { name: 'Brainfuck', lang: 'brainfuck' },
  { name: 'C#', lang: 'csharp' },
  { name: 'C', lang: 'c' },
  { name: 'C++', lang: 'cpp' },
  { name: 'C/AL', lang: 'cal' },
  { name: 'Cache Object Script', lang: 'cos' },
  { name: 'CMake', lang: 'cmake' },
  { name: 'Coq', lang: 'coq' },
  { name: 'CSP', lang: 'csp' },
  { name: 'CSS', lang: 'css' },
  { name: 'Cap’n Proto', lang: 'capnproto' },
  { name: 'Clojure', lang: 'clojure' },
  { name: 'CoffeeScript', lang: 'coffeescript' },
  { name: 'Crmsh', lang: 'crmsh' },
  { name: 'Crystal', lang: 'crystal' },
  { name: 'D', lang: 'd' },
  { name: 'Dart', lang: 'dart' },
  { name: 'Delphi', lang: 'dpr' },
  { name: 'Diff', lang: 'diff' },
  { name: 'Django', lang: 'django' },
  { name: 'DNS Zone file', lang: 'dns' },
  { name: 'Dockerfile', lang: 'dockerfile' },
  { name: 'DOS', lang: 'dos' },
  { name: 'dsconfig', lang: 'dsconfig' },
  { name: 'DTS (Device Tree)', lang: 'dts' },
  { name: 'Dust', lang: 'dust' },
  { name: 'EBNF', lang: 'ebnf' },
  { name: 'Elixir', lang: 'elixir' },
  { name: 'Elm', lang: 'elm' },
  { name: 'Erlang', lang: 'erlang' },
  { name: 'Excel', lang: 'excel' },
  { name: 'F#', lang: 'fsharp' },
  { name: 'FIX', lang: 'fix' },
  { name: 'Fortran', lang: 'fortran' },
  { name: 'G-Code', lang: 'gcode' },
  { name: 'Gams', lang: 'gams' },
  { name: 'GAUSS', lang: 'gauss' },
  { name: 'Gherkin', lang: 'gherkin' },
  { name: 'Go', lang: 'go' },
  { name: 'Golo', lang: 'golo' },
  { name: 'Gradle', lang: 'gradle' },
  { name: 'Groovy', lang: 'groovy' },
  { name: 'HTML, XML', lang: 'xml' },
  { name: 'HTTP', lang: 'http' },
  { name: 'Haml', lang: 'haml' },
  { name: 'Handlebars', lang: 'handlebars' },
  { name: 'Haskell', lang: 'haskell' },
  { name: 'Haxe', lang: 'haxe' },
  { name: 'Hy', lang: 'hy' },
  { name: 'Ini, TOML', lang: 'ini' },
  { name: 'Inform7', lang: 'inform7' },
  { name: 'IRPF90', lang: 'irpf90' },
  { name: 'JSON', lang: 'json' },
  { name: 'Java', lang: 'java' },
  { name: 'JavaScript', lang: 'javascript' },
  { name: 'Julia', lang: 'julia' },
  { name: 'Kotlin', lang: 'kotlin' },
  { name: 'LaTeX', lang: 'tex' },
  { name: 'Leaf', lang: 'leaf' },
  { name: 'Lasso', lang: 'lasso' },
  { name: 'Less', lang: 'less' },
  { name: 'LDIF', lang: 'ldif' },
  { name: 'Lisp', lang: 'lisp' },
  { name: 'LiveCode Server', lang: 'livecodeserver' },
  { name: 'LiveScript', lang: 'livescript' },
  { name: 'Lua', lang: 'lua' },
  { name: 'Makefile', lang: 'makefile' },
  { name: 'Markdown', lang: 'markdown' },
  { name: 'Mathematica', lang: 'mathematica' },
  { name: 'Matlab', lang: 'matlab' },
  { name: 'Maxima', lang: 'maxima' },
  { name: 'Maya Embedded Language', lang: 'mel' },
  { name: 'Mercury', lang: 'mercury' },
  { name: 'Mizar', lang: 'mizar' },
  { name: 'Mojolicious', lang: 'mojolicious' },
  { name: 'Monkey', lang: 'monkey' },
  { name: 'Moonscript', lang: 'moonscript' },
  { name: 'N1QL', lang: 'n1ql' },
  { name: 'NSIS', lang: 'nsis' },
  { name: 'Nginx', lang: 'nginx' },
  { name: 'Nim', lang: 'nim' },
  { name: 'Nix', lang: 'nix' },
  { name: 'OCaml', lang: 'ocaml' },
  { name: 'Objective C', lang: 'objectivec' },
  { name: 'OpenGL Shading Language', lang: 'glsl' },
  { name: 'OpenSCAD', lang: 'openscad' },
  { name: 'Oracle Rules Language', lang: 'ruleslanguage' },
  { name: 'Oxygene', lang: 'oxygene' },
  { name: 'PF', lang: 'pf' },
  { name: 'PHP', lang: 'php' },
  { name: 'Parser3', lang: 'parser3' },
  { name: 'Perl', lang: 'perl' },
  { name: 'Pony', lang: 'pony' },
  { name: 'PostgreSQL & PL/pgSQL', lang: 'pgsql' },
  { name: 'PowerShell', lang: 'powershell' },
  { name: 'Processing', lang: 'processing' },
  { name: 'Prolog', lang: 'prolog' },
  { name: 'Properties', lang: 'properties' },
  { name: 'Protocol Buffers', lang: 'protobuf' },
  { name: 'Puppet', lang: 'puppet' },
  { name: 'Python', lang: 'python' },
  { name: 'Python profiler results', lang: 'profile' },
  { name: 'Python REPL', lang: 'python-repl' },
  { name: 'Q', lang: 'k' },
  { name: 'QML', lang: 'qml' },
  { name: 'R', lang: 'r' },
  { name: 'ReasonML', lang: 'reasonml' },
  { name: 'RenderMan RIB', lang: 'rib' },
  { name: 'RenderMan RSL', lang: 'rsl' },
  { name: 'Roboconf', lang: 'graph' },
  { name: 'Ruby', lang: 'ruby' },
  { name: 'Rust', lang: 'rust' },
  { name: 'SAS', lang: 'sas' },
  { name: 'SCSS', lang: 'scss' },
  { name: 'SQL', lang: 'sql' },
  { name: 'STEP Part 21', lang: 'p21' },
  { name: 'Scala', lang: 'scala' },
  { name: 'Scheme', lang: 'scheme' },
  { name: 'Scilab', lang: 'scilab' },
  { name: 'Shell', lang: 'shell' },
  { name: 'Smali', lang: 'smali' },
  { name: 'Smalltalk', lang: 'smalltalk' },
  { name: 'SML', lang: 'sml' },
  { name: 'Stan', lang: 'stan' },
  { name: 'Stata', lang: 'stata' },
  { name: 'Stylus', lang: 'stylus' },
  { name: 'SubUnit', lang: 'subunit' },
  { name: 'Swift', lang: 'swift' },
  { name: 'Tcl', lang: 'tcl' },
  { name: 'Test Anything Protocol', lang: 'tap' },
  { name: 'Thrift', lang: 'thrift' },
  { name: 'TP', lang: 'tp' },
  { name: 'Twig', lang: 'twig' },
  { name: 'TypeScript', lang: 'typescript' },
  { name: 'VB.Net', lang: 'vbnet' },
  { name: 'VBScript', lang: 'vbscript' },
  { name: 'VHDL', lang: 'vhdl' },
  { name: 'Vala', lang: 'vala' },
  { name: 'Verilog', lang: 'verilog' },
  { name: 'Vim Script', lang: 'vim' },
  { name: 'X++', lang: 'axapta' },
  { name: 'x86 Assembly', lang: 'x86asm' },
  { name: 'XL', lang: 'xl' },
  { name: 'XQuery', lang: 'xquery' },
  { name: 'YAML', lang: 'yml' },
  { name: 'Zephir', lang: 'zephir' },
];
